[package]
name = "opal"
version = "0.1.0"
edition = "2024"

[dependencies]
elsa = "1.11.2"
strum = { version = "0.27.2", features = ["derive"] }
opal_proc = { path = "../opal_proc" }
colored = "3.1.1"

[dev-dependencies]
libtest-mimic = "0.8.1"
opal_proc = { path = "../opal_proc" }

[lib]
test = false
doctest = false

[[test]]
name = "integration"
harness = false
